const cars = [
  {
    make: 'Toyota',
    model: 'Camry',
    package: 'LE',
    color: 'Silver',
    year: '2022',
    category: 'Sedan',
    mileage: '15000',
    price: 2500000,
    id: 1,
  },
  {
    make: 'Honda',
    model: 'Civic',
    package: 'EX',
    color: 'Blue',
    year: '2021',
    category: 'Sedan',
    mileage: '20000',
    price: 2200000,
    id: 2,
  },
  {
    make: 'Ford',
    model: 'F-150',
    package: 'Lariat',
    color: 'Black',
    year: '2020',
    category: 'Truck',
    mileage: '25000',
    price: 3500000,
    id: 3,
  },
  {
    make: 'Chevrolet',
    model: 'Equinox',
    package: 'LT',
    color: 'Red',
    year: '2019',
    category: 'SUV',
    mileage: '18000',
    price: 2800000,
    id: 4,
  },
  {
    make: 'Nissan',
    model: 'Rogue',
    package: 'SV',
    color: 'White',
    year: '2022',
    category: 'SUV',
    mileage: '12000',
    price: 2600000,
    id: 5,
  },
  {
    make: 'BMW',
    model: 'X5',
    package: 'xDrive40i',
    color: 'Gray',
    year: '2021',
    category: 'SUV',
    mileage: '10000',
    price: 4500000,
    id: 6,
  },
  {
    make: 'Toyota',
    model: 'Corolla',
    package: 'SE',
    color: 'Blue',
    year: '2020',
    category: 'Sedan',
    mileage: '22000',
    price: 2000000,
    id: 7,
  },
  {
    make: 'Ford',
    model: 'Mustang',
    package: 'GT',
    color: 'Yellow',
    year: '2018',
    category: 'Sports Car',
    mileage: '18000',
    price: 3000000,
    id: 8,
  },
  {
    make: 'Honda',
    model: 'Pilot',
    package: 'Touring',
    color: 'Black',
    year: '2019',
    category: 'SUV',
    mileage: '16000',
    price: 3200000,
    id: 9,
  },
  {
    make: 'Chevrolet',
    model: 'Camaro',
    package: 'SS',
    color: 'Red',
    year: '2023',
    category: 'Sports Car',
    mileage: '5000',
    price: 4000000,
    id: 10,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    package: 'Performance',
    color: 'White',
    year: '2022',
    category: 'Electric',
    mileage: '8000',
    price: 5500000,
    id: 11,
  },
  {
    make: 'Toyota',
    model: 'Highlander',
    package: 'Limited',
    color: 'Silver',
    year: '2021',
    category: 'SUV',
    mileage: '14000',
    price: 3800000,
    id: 12,
  },
  {
    make: 'Audi',
    model: 'A4',
    package: 'Premium Plus',
    color: 'Black',
    year: '2020',
    category: 'Sedan',
    mileage: '17000',
    price: 2800000,
    id: 13,
  },
  {
    make: 'Subaru',
    model: 'Outback',
    package: 'Touring',
    color: 'Green',
    year: '2019',
    category: 'Wagon',
    mileage: '19000',
    price: 2400000,
    id: 14,
  },
  {
    make: 'Ford',
    model: 'Escape',
    package: 'SE',
    color: 'Gray',
    year: '2023',
    category: 'SUV',
    mileage: '6000',
    price: 2700000,
    id: 15,
  },
  {
    make: 'Chevrolet',
    model: 'Silverado',
    package: 'LT',
    color: 'Blue',
    year: '2022',
    category: 'Truck',
    mileage: '10000',
    price: 3800000,
    id: 16,
  },
  {
    make: 'Jeep',
    model: 'Wrangler',
    package: 'Rubicon',
    color: 'Orange',
    year: '2021',
    category: 'SUV',
    mileage: '12000',
    price: 3500000,
    id: 17,
  },
  {
    make: 'Mazda',
    model: 'CX-5',
    package: 'Grand Touring',
    color: 'Red',
    year: '2020',
    category: 'SUV',
    mileage: '15000',
    price: 2600000,
    id: 18,
  },
  {
    make: 'Volkswagen',
    model: 'Golf',
    package: 'SE',
    color: 'White',
    year: '2019',
    category: 'Hatchback',
    mileage: '17000',
    price: 2200000,
    id: 19,
  },
  {
    make: 'Kia',
    model: 'Seltos',
    package: 'SX',
    color: 'Gray',
    year: '2023',
    category: 'SUV',
    mileage: '3000',
    price: 2500000,
    id: 20,
  },
];

module.exports = cars;
